source 'https://rubygems.org'

gem 'middleman', '>= 4.0.0'
gem 'middleman-dato'
gem 'middleman-paginate'
gem 'middleman-livereload'
gem 'middleman-search_engine_sitemap'
gem 'middleman-minify-html'
gem 'pry'
gem 'slim'
gem 's3_website'
